[package]
name = "pg-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
merkle_hash = "3.6.1"
rstest = "0.18.2"
termsize = "0.1.6"
users = "0.11.0"
